In [2]:
list_two = list(range(1,4))
list_three = list(range(1,4))
list_sum = []

for index in range(3):
    list_two[index] = list_two[index] ** 2
    list_three[index] = list_three[index] ** 3
    list_sum.append(list_two[index] + list_three[index])
    print(list_sum)

[2]
[2, 12]
[2, 12, 36]


In [20]:
import numpy as np
list_new = np.arange(1,4) ** 2
list_new2 = np.arange(1,4) ** 3
print(list_new + list_new2)


[ 2 12 36]


In [7]:
np.power(np.array([1,2,3]), 3)

array([ 1,  8, 27])

In [11]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)

multi_array = np.array([x,y,z])
print(multi_array)
print(multi_array.shape)
print(multi_array[1,0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
3


In [9]:
"""How to create an array using linspace method"""
test_array = np.linspace(1,20, 50)
print(test_array)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [21]:
"""How to perform mathematical operations between arrays """
a = np.arange(3) ** 2
b = np.arange(3) ** 3
print( a + b)

[ 0  2 12]


In [29]:
"""convert a list to an array """
a = list(range(3))
b = list(range(3))

my_array = np.array(a) + np.array(b)
my_array

array([0, 2, 4])

In [32]:
"""how to slice an array"""
array = np.arange(9)
print(array[2:4])


[2 3]


In [36]:
"""how to slice multi-dimensional array"""
array = np.arange(9).reshape(3,3)
array
print(array[:1,:2])

[[0 1]]


In [46]:
"""ravel method turns a multi dimensional array into a uni dimensional array an shows it's view(does not create a new array)"""
x = np.arange(9).reshape(3,3)
print(x.ravel())


[0 1 2 3 4 5 6 7 8]


In [47]:
"""flat() method allocates new memory and creates a copy of the array"""
x = np.arange(9).reshape(3,3)
print(x.flatten())

[0 1 2 3 4 5 6 7 8]


In [48]:
"""transpose"""
print(x.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [56]:
"""multiplication of matrices"""
import numpy as np
mat_a = np.matrix([1,2,3,4,5,6]).reshape(2,3)
print(mat_a)

[[1 2 3]
 [4 5 6]]


In [57]:
mat_b = np.matrix([3,4,3,-2,4,-2]).reshape(3,2)
print(mat_b)



[[ 3  4]
 [ 3 -2]
 [ 4 -2]]


In [58]:
print(mat_a * mat_b)

[[21 -6]
 [51 -6]]


In [59]:
"""stacking arrays horizontally, number of columns must be same"""
x = np.arange(4).reshape(2,2)
x

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [60]:
y = np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [61]:
z = np.hstack((x,y))
z

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [62]:
"""stacking arrays vertically, number of rows must be same"""
x = np.arange(4).reshape(2,2)
x

array([[0, 1],
       [2, 3]])

In [63]:
y = np.arange(4,8).reshape(2,2)
y

array([[4, 5],
       [6, 7]])

In [64]:
z = np.vstack((x,y))
z

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [67]:
d = np.dstack((x,y))
d


array([[[0, 4],
        [1, 5]],

       [[2, 6],
        [3, 7]]])

In [66]:
print(d.shape)

(2, 2, 2)


In [69]:
"""horizontal stack is the same as column stack"""
c = np.column_stack((x,y))
c


array([[0, 1, 4, 5],
       [2, 3, 6, 7]])